server {
    listen 80;

    # Gzip para acelerar transferencia de assets
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 1024;

    # Frontend estático — Nginx sirve directo desde disco
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # API — proxy a Node.js
    location /api/ {
        proxy_pass http://fitmeal-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /auth/ {
        proxy_pass http://fitmeal-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api-docs {
        proxy_pass http://fitmeal-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /exercises/ {
        alias /usr/share/nginx/exercises/;
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
}
